server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servicelink?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: sluser
    password: slpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
springdoc:
  swagger-ui:
    path: /swagger-ui
app:
  jwt:
    secret: ${JWT_SECRET:change-this-very-long-secret-12345678901234567890}
    expiration-seconds: 36000
